db:
  one: db0

spring:
  shardingsphere:
    #数据源名称
    datasource:
      names: ${db.one}
      #数据源db01连接信息
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        #type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name=com: com.mysql.jdbc.Driver
        #driver-class-name=com: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/sharding_jdbc?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        maxPoolSize: 20
    ##配置分片规则，参见https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/configuration/yaml/sharding/
    sharding:
      tables:
        user:
          #配置 user 表规则
          actual-data-nodes: db0.user_$->{0..2}
          ## 配置分表策略
          table-strategy:
            inline:
              #分片列名称，多个列以逗号分隔
              sharding-column: id
              algorithm-expression: user_$->{id % 2}
    #打印SQL
    props:
      sql:
        show: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml